"""users table

Revision ID: 5654e2b6df78
Revises: 
Create Date: 2018-09-06 18:41:09.384316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5654e2b6df78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.TEXT(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('date', mysql.TEXT(), nullable=False),
    sa.Column('author', mysql.TEXT(), nullable=False),
    sa.Column('tags', mysql.TEXT(), nullable=False),
    sa.Column('views', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
